// <auto-generated />
using System;
using GerenciamentoProducao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciamentoProducaoo.Migrations
{
    [DbContext(typeof(GerenciamentoProdDbContext))]
    [Migration("20250925005416_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GerenciamentoProducao.Models.Caixilho", b =>
                {
                    b.Property<int>("IdCaixilho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCaixilho"));

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<int?>("FamiliaCaixilhoIdFamiliaCaixilho")
                        .HasColumnType("int");

                    b.Property<int>("IdFamiliaCaixilho")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoCaixilho")
                        .HasColumnType("int");

                    b.Property<int>("Largura")
                        .HasColumnType("int");

                    b.Property<string>("NomeCaixilho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<float>("PesoUnitario")
                        .HasColumnType("real");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int?>("TipoCaixilhoIdTipoCaixilho")
                        .HasColumnType("int");

                    b.HasKey("IdCaixilho");

                    b.HasIndex("FamiliaCaixilhoIdFamiliaCaixilho");

                    b.HasIndex("ObraId");

                    b.HasIndex("TipoCaixilhoIdTipoCaixilho");

                    b.ToTable("Caixilho");
                });

            modelBuilder.Entity("GerenciamentoProducao.Models.FamiliaCaixilho", b =>
                {
                    b.Property<int>("IdFamiliaCaixilho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFamiliaCaixilho"));

                    b.Property<string>("DescricaoFamilia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PesoTotal")
                        .HasColumnType("int");

                    b.HasKey("IdFamiliaCaixilho");

                    b.ToTable("FamiliaCaixilho");
                });

            modelBuilder.Entity("GerenciamentoProducao.Models.Obra", b =>
                {
                    b.Property<int>("IdObra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObra"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Construtora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdObra");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Obra");
                });

            modelBuilder.Entity("GerenciamentoProducao.Models.Producao", b =>
                {
                    b.Property<int>("IdProducao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducao"));

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EhLiberado")
                        .HasColumnType("bit");

                    b.Property<int>("FamiliaCaixilhoId")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NomeProducao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Produzido")
                        .HasColumnType("bit");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdProducao");

                    b.HasIndex("FamiliaCaixilhoId");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Producao");
                });

            modelBuilder.Entity("GerenciamentoProducao.Models.TipoCaixilho", b =>
                {
                    b.Property<int>("IdTipoCaixilho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoCaixilho"));

                    b.Property<string>("DescricaoCaixilho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoCaixilho");

                    b.ToTable("TipoCaixilho");
                });

            modelBuilder.Entity("GerenciamentoProducao.Models.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoUsuario"));

                    b.Property<string>("NomeTipoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("GerenciamentoProducao.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int?>("TipoUsuarioIdTipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("TipoUsuarioIdTipoUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("GerenciamentoProducao.Models.Caixilho", b =>
                {
                    b.HasOne("GerenciamentoProducao.Models.FamiliaCaixilho", "FamiliaCaixilho")
                        .WithMany()
                        .HasForeignKey("FamiliaCaixilhoIdFamiliaCaixilho");

                    b.HasOne("GerenciamentoProducao.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciamentoProducao.Models.TipoCaixilho", "TipoCaixilho")
                        .WithMany()
                        .HasForeignKey("TipoCaixilhoIdTipoCaixilho");

                    b.Navigation("FamiliaCaixilho");

                    b.Navigation("Obra");

                    b.Navigation("TipoCaixilho");
                });

            modelBuilder.Entity("GerenciamentoProducao.Models.Obra", b =>
                {
                    b.HasOne("GerenciamentoProducao.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GerenciamentoProducao.Models.Producao", b =>
                {
                    b.HasOne("GerenciamentoProducao.Models.FamiliaCaixilho", "FamiliaCaixilho")
                        .WithMany()
                        .HasForeignKey("FamiliaCaixilhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciamentoProducao.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("FamiliaCaixilho");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GerenciamentoProducao.Models.Usuario", b =>
                {
                    b.HasOne("GerenciamentoProducao.Models.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("TipoUsuarioIdTipoUsuario");

                    b.Navigation("TipoUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
